### MangoHud configuration

### Default options 
gpu_stats
cpu_stats
fps
frametime
frame_timing

no_display

round_corners=5
font_size=20
text_outline=no
text_color=F0EDE0
background_color=0A0815
gpu_color=8FF0A4
cpu_color=99C1F1

cpu_temp
gpu_junction_temp

fps_text=FPS
fps_sampling_period=500
fps_metrics=avg,0.01

throttling_status_graph

toggle_hud=Alt_L+grave
reset_fps_metrics=Control_L+r

offset_x=8
offset_y=30
