general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 300 # 5 min
    on-timeout = loginctl lock-session
}

# listener {
#     timeout = 900 # 15 min
#     on-timeout = niri msg action power-off-monitors
#     on-resume = niri msg action power-on-monitors
# }

listener {
    timeout = 600 # 10 min
    on-timeout = powerprofilesctl set power-saver
    on-resume = powerprofilesctl set balanced
}
