
[*code]
f9 = A-j
f10 = A-l

[kitty*]
control.u = C-u
control.r = C-r
control.enter = A-enter
shift.backspace = S-delete
control.backspace = S-delete

[*firefox]
alt.d = A-S-d
alt.n = C-t
alt.q = C-w
meta.n = C-n
control.b = C-d
alt.z = f11
alt./ = f12
alt.v = A-S-8
control.g = A-S-2
alt.backspace = A-S-7
meta+shift.n = C-S-p
alt.s = A-S-3
alt.c = f6
alt.f = C-S-]

alt.b = macro(C-k backspace * space)
alt.t = macro(C-k backspace % space)
alt.h = macro(C-k backspace ^ space)
alt., = macro(C-t about:preferences enter)
alt.a = macro(C-t about:addons enter)

control+shift.s = A-c
control+shift.w = A-w

[*nautilus]
control.h = f2
alt.n = C-t
alt.q = C-w
alt.l = C-tab
alt.j = C-S-tab
alt.c = C-l
alt.r = C-S-t

control+shift.i = S-up
control+shift.j = S-left
control+shift.k = S-down
control+shift.l = S-right

[*xournalpp]
alt.c = f9
alt.m = f10
shift.i = S-k
shift.k = S-j
# [minecraft*],
# [*-exe],
[steam*]
f9 = pagedown
f10 = pageup
control = rightalt
capslock = layer(control)
meta = overload(meta, noop)
esc = esc

control.d = C-d
control.u = C-u
control.r = C-r

leftalt = layer(alt)
rightalt = layer(altgr)

[starcitizen*]
alt.z = macro(z+0 20ms z)
alt.f = macro(y 20ms y)

[minecraft*]
mouse1 = 2
mouse2 = 1
f3 = 9
