[ids]
*

[global]
oneshot_timeout = 250
overload_tap_timeout = 1000
macro_sequence_timeout = 10000
layer_indicator = 1

[main]
# <C-> when chained, Esc on tap:
capslock = overload(control, esc)
leftmeta = overload(meta, search)
# Double-tap alt(s) for forward, back
leftalt = overload(alt, oneshot(back))
rightalt = overload(altgr, oneshot(forward))
esc = home

# Mouse (via ratbag):
f5 = previoussong
f6 = nextsong
f9 = C-S-tab
f10 = C-tab

[back]
leftalt = overloadt(alt, A-left, 150)

[forward]
rightalt = overloadt(altgr, A-right, 150)

[control]
i = up
j = left
k = down
l = right

d = delete
u = C-z
r = C-S-z

[shift]
backspace = C-backspace

[alt]
- = —
space = ⠀

[altgr]
i = A-S-]
k = A-S-[
j = A-[
l = A-]

[meta+altgr]
i = M-S-]
k = M-S-[
j = M-[
l = M-]

# Override text selection; word navigation
[control+shift]
i = C-up
j = C-left
k = C-down
l = C-right

[control+alt] 
i = C-A-up
j = C-A-left
k = C-A-down
l = C-A-right

[meta]
f9 = M-f9
f10 = M-f10
capslock = overload(control, command(wm toggle-window-floating))
r = C-r

# Define for app.conf:
[meta+shift]

[alt+shift]

[meta+control]
i = M-C-i
j = M-C-j
k = M-C-k
l = M-C-l

[meta+control+shift]
i = M-C-S-i
j = M-C-S-j
k = M-C-S-k
l = M-C-S-l

[meta+alt]
i = M-A-i
j = M-A-j
k = M-A-k
l = M-A-l
