#!/bin/bash

perc=$([ $DEV_TYPE = "lap" ] && acpi -b | grep -v 'rate' | cut -d' ' -f 3-) # internal
# echo -e "$(hostname):\t\t${perc:-N/A}"
[ -z "$perc" ] || echo -e "$perc\n"

bluetoothctl devices | while read -r _ mac name; do
    path=$(upower -e | grep -i "${mac//:/_}")
    if [ -n "$path" ]; then
        perc=$(upower -i "$path" | awk '/percentage:/ {print $2}')
        echo -e "$name: $perc"
    fi
done

if [ "$(adb get-state 2> /dev/null)" = "device" ]; then
    name=$(adb shell settings get global device_name)
    echo "$name: $(adb shell acpi 2> /dev/null | grep -oP "\d+%")"
fi
