#!/bin/bash
ADDR=$(bluetoothctl devices Connected | grep $1 | cut -d ' ' -f 2)
if [ -z "$ADDR" ]; then
	ADDR=$(bluetoothctl devices | grep $1 | cut -d ' ' -f 2)
	bluetoothctl connect $ADDR
else
	bluetoothctl disconnect $ADDR
fi
