#!/bin/bash
if [ -z "$1" ]; then
	bluetoothctl devices Connected | cut -d' ' -f 3-
	exit
fi

ADDR=$(bluetoothctl devices Connected | grep $1 | cut -d ' ' -f 2)
if [ -z "$ADDR" ]; then
	ADDR=$(bluetoothctl devices | grep $1 | cut -d ' ' -f 2)
	bluetoothctl connect $ADDR
else
	bluetoothctl disconnect $ADDR
fi
