#!/bin/sh

event_focusedmon() { # Relocate widgets
  sh $DOTS/scripts/widget.sh mon
}

event_monitoradded() { # Enter desktop mode
    hyprctl dispatch "focusmonitor $MONITORNAME"
    pkill -f idle-lap.sh && pkill -f rotate.sh && pkill -f swayidle
    hyprctl keyword monitor "eDP-1, disable"
    sudo modprobe -r intel_ish_ipc
    # TODO: kbd *still* disables @ 360deg
}

event_monitorremoved() {
    hyprctl dispatch "focusmonitor eDP-1"
    pgrep -f "idle-lap.sh" || sh $DOTS/scripts/idle.sh &
    pgrep -f "rotate.sh" || sh $DOTS/scripts/rotate.sh &
    hyprctl keyword monitor "eDP-1, enable"
    sudo modprobe intel_ish_ipc
}
