#!/bin/bash
MUSIC="/home/bren/audio/Spotify"
find $MUSIC -type f -name "*.spotdl" | while read path
do
  dir=$(dirname "$path")
  file=$(basename "$path")
  cd "$dir" || exit
  spotdl sync "$file" --preload --thread 8 --scan-for-songs --overwrite skip --dont-filter-results 
  cd .. || exit
done
notify-send -u low -i - "Spotify" "Local sync complete"
