#!/usr/bin/env python
"""
Window swapper:
- if swap against workspace edge, move it to next workspace
- if move would exceed fixed workspace count, do nothing
- option: follow to new workspace only if active empty
- shift: swap immediate
"""
from subprocess import getoutput as run
from sys import argv as args
from json import loads as load
from re import search

windows = load(run("hyprctl clients -j"))
active = load(run("hyprctl activewindow -j"))
workspace = load(run("hyprctl activeworkspace -j"))
nWin = workspace["windows"] - (len(active["grouped"])-1 if active["grouped"] else 0)
if nWin == 0: exit()

shift = True if search("S-", args[1]) else False
dir = search(r"(?:^|[SMAC]-)([uldr])$", args[1])
dir = dir.group(1) if dir else ""

if dir == 'u' or dir == 'd': run(f"hyprctl dispatch swapwindow {dir}"); exit()
for w in windows:
    if shift or nWin == 1 or active["floating"]: break
    if w["address"] in active["grouped"] or w["pid"] == -1 \
    or w["workspace"]["id"] != active["workspace"]["id"] \
    or w["floating"] == 1: continue

    if dir == 'l' and active["at"][0] > w["at"][0] \
    or dir == 'r' and active["at"][0] < w["at"][0]: 
        run(f"hyprctl dispatch swapwindow {dir}"); exit()

# silent = "silent" if nWin > 1 else ""
silent = ""
run(f"hyprctl dispatch denywindowfromgroup on")
if dir == 'l' and active["workspace"]["id"] > 1:
    run(f"hyprctl dispatch movetoworkspace{silent} -1")
if dir == 'r' and active["workspace"]["id"] < 3: 
    run(f"hyprctl dispatch movetoworkspace{silent} +1")
run(f"hyprctl dispatch denywindowfromgroup off")

