#!/usr/bin/env python

from subprocess import getoutput as run
import re
# from sys import argv

# args = " ".join(argv[1:])

run("echo key ctrl+c | dotool")
clip = run("cliphist list | head -n 1 | cliphist decode")
# run(f'notify-send "{clip}"')
run(f'cliphist delete-query "{clip}"')

clean = re.sub(r'(?<=\S)-\n', r'', clip)
clean = re.sub('\n(?!\n)', r' ', clean)

print(clean)

# run(f'edge-playback --text "{clip}" {args}')
run(f'edge-playback --text "{clean}" --rate=+100% --voice en-US-EricNeural')
