# /etc/zshenv: system-wide .zshenv file

# —— PATHS ——————————————————————

export HOME=~
export DOTS="$HOME/dots"
export SCRIPTS="$DOTS/scripts"
export CACHE="$HOME/.cache"
export CONFIG="$HOME/.config"
export DL="$HOME/dl"

source /etc/os-release

if [ -n "$(ls /sys/class/power_supply | grep -E '^BAT')" ]
    then export DEV_TYPE="lap"; else export DEV_TYPE="desk"
fi

profile_d="/nix/var/nix/profiles/default/etc/profile.d"
if [ -e "$profile_d/nix-daemon.sh" ]; then
  . "$profile_d/nix-daemon.sh"
fi

export PNPM_HOME="$HOME/.local/share/pnpm"
export ZDOTDIR="$HOME/.config/zsh"
export DOTFILES_REPO_PATH="$DOTS"
export WINEPREFIX="$HOME/.games"

typeset -U PATH path
path+=(
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
    "$HOME/.cabal/bin"
    "$HOME/.ghcup/bin"
    "$(go env GOPATH)/bin"
    "$PNPM_HOME"
)
export PATH

# —— VARS ———————————————————————

source $HOME/.env

export WORDCHARS=""
export ZSHZ_OWNER="$USER"
export PROMPT_EOL_MARK=""
export EDITOR="nvim"
export SUDO_PROMPT="Password: "

export BAT_THEME="base16"
export GREP_COLORS="ms=1;30;43"
export RG_COLORS="--colors 'match:bg:yellow' --colors 'match:fg:black'"
export LS_COLORS="${LS_COLORS}:di=0;37:*.py=01;32:ln=04:*.md=36:ex=0:"
export MANPAGER="nvim -c 'let g:no_man_maps = 1' -c 'Man!' -"
export MANROFFOPT="-c"
export TIMEFMT=$'\n%*Es'
export LESS="-FSXKR" LESSHISTFILE=-
export FZF_DEFAULT_COMMAND="fd -L --type f"
export FZF_DEFAULT_OPTS="
--height=20 --info=inline-right --exit-0 --select-1 --color "hl+:-1:reverse" --ansi
--preview-window='top,40%' --layout=reverse --prompt='› ' --pointer=█ --marker=▍
--bind 'shift-delete:backward-kill-word'
--bind 'C:execute-silent(wl-copy "{+}" --trim-newline)'
--bind 'alt-p:change-preview-window(hidden|top)'"
export _ZO_FZF_OPTS=$FZF_DEFAULT_OPTS
export XCURSOR_PATH="$HOME/.local/share/icons"
export XCURSOR_SIZE=32 XCURSOR_THEME="Google"

export _ZO_RESOLVE_SYMLINKS=1 
export HSA_OVERRIDE_GFX_VERSION=10.3.0
export ELECTRON_OZONE_PLATFORM_HINT=auto
