# —— INIT ———————————————————————

autoload -Uz compinit
zstyle ':completion:*' menu yes select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':zcomet:compinit' dump-file $ZDOTDIR/.dump
zstyle ':zcomet:compinit' arguments -i
zmodload zsh/complist
_comp_options+=(globdots)        # Include hidden files
zle_highlight=('paste:none')
autoload -Uz colors && colors    # Colors

source $ZDOTDIR/alias.zsh               # aliases
if [[ ! -f ${ZDOTDIR}/.zcomet/bin/zcomet.zsh ]]; then
  command git clone https://github.com/agkozak/zcomet.git ${ZDOTDIR:-${HOME}}/.zcomet/bin
fi
source $ZDOTDIR/.zcomet/bin/zcomet.zsh  # plugin manager
source $DOTS/zsh/zshenv                 # env vars (re-source)
eval "$(direnv hook zsh)"
ulimit -S -n 2048

[[ -z "$WAYLAND_DISPLAY" && "$(tty)" = "/dev/tty1" ]] && exec niri-session

autoload -Uz bracketed-paste-url-magic  # handle unquoted URLs
zle -N bracketed-paste bracketed-paste-url-magic
autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

# —— PROMPT —————————————————————

export VIRTUAL_ENV_DISABLE_PROMPT=1
setopt PROMPT_SUBST
autoload -Uz vcs_info
preexec() { print -Pn "\e]2;$1\a" }
precmd() { vcs_info; print -Pn "\e]2;%1~\a" }
zstyle ':vcs_info:git:*' formats ' %F{8}@ %f%F{4}%b%f'

venv_status() { [[ -n "$VIRTUAL_ENV" ]] && echo "%F{8}($(basename $VIRTUAL_ENV))%f " }

[[ $EUID -eq 0 ]] && PROMPT="%F{1}»%f " || PROMPT="%F{246}›%f "
RPROMPT='$(venv_status)%F{240}%1~%f${vcs_info_msg_0_}'

# —— EXTS ———————————————————————

load zsh-users/zsh-completions
load ohmyzsh plugins/dirhistory
load ohmyzsh plugins/sudo

eval "$(zoxide init zsh --cmd g)"
zcomet compinit

load RobSis/zsh-completion-generator
load Aloxaf/fzf-tab

# load marlonrichert/zsh-autocomplete
load zsh-users/zsh-autosuggestions
load zsh-users/zsh-syntax-highlighting
# load zdharma-continuum/fast-syntax-highlighting

# —— KEYS ———————————————————————

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^[e' edit-command-line

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey '^[' autosuggest-clear

bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^H'      backward-kill-word
bindkey '^[^?' clear-screen
bindkey '^[h' hist
bindkey '^[f' files
bindkey '^[F' dirs
bindkey '^[[3;3~' hunt
bindkey '^e'  fm

# —— OPTIONS ————————————————————                                                        
                                                                                         
unsetopt BEEP                                                                            
unsetopt NOMATCH                 # Pass unmatched globs literally
setopt AUTO_CD                                                                           
setopt GLOB_DOTS                                                                         
setopt MENU_COMPLETE                                                                     
setopt INTERACTIVE_COMMENTS                                                              
                                                                                         
HISTFILE=$ZDOTDIR/.hist                                                                  
HISTSIZE=50000                                                                           
SAVEHIST=50000                                                                           
                                                                                         
setopt EXTENDED_HISTORY          # Write in ":start:elapsed;command" format                 
setopt SHARE_HISTORY             # Share history between sessions
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY               # Don't execute immediately upon history expansion      

stty stop undef                  # Prevent C-s from freezing terminal 
